sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    music.play(music.createSong(assets.song`First_Song`), music.PlaybackMode.UntilDone)
    scene.setBackgroundImage(assets.image`Road`)
    mySprite4.setPosition(23, 71)
})
let mySprite4: Sprite = null
effects.starField.startScreenEffect()
scene.setBackgroundImage(assets.image`Stage`)
game.setDialogTextColor(15)
game.showLongText("Press A to start", DialogLayout.Center)
scene.setBackgroundImage(assets.image`Winter_Tree_Background_Night`)
game.setDialogTextColor(15)
mySprite4 = sprites.create(assets.image`Snow`, SpriteKind.Player)
mySprite4.setPosition(123, 88)
mySprite4.setBounceOnWall(true)
controller.moveSprite(mySprite4, 100, 100)
info.setLife(100)
let mySprite2 = sprites.create(assets.image`Ghost`, SpriteKind.Enemy)
